name: Convert DEV Posts to Jekyll Markdown
#on:
 #schedule:
     # At midnight twice a week on Monday and Thursday
  #  - cron:  '0 0 * * 1,4'
on:
  issues:
    types: [opened, edited] 
jobs:
  dev-to-jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: dev-to-jekyll
      uses: benhayehudi/dev-posts-to-jekyll-markdown-action@use-axios
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_API_KEY: "${{ secrets.DEV_API_KEY }}"
      NUM_OF_POSTS: "${{ secrets.NUM_OF_POSTS }}"